/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type BroadcastTxResponse struct {

	// Txid of successfully broadcasted transaction
	Txid string `json:"txid,omitempty"`
}
