/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type BurnTokenRequestBurn struct {

	// Amount of tokens to burn
	Amount float32 `json:"amount,omitempty"`

	// Unique token id we are burning
	TokenId string `json:"tokenId,omitempty"`
}
