/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GetAddressUtxosResponseInner struct {

	// Address
	Address string `json:"address,omitempty"`

	// Transaction ID
	Txid string `json:"txid,omitempty"`

	// vout
	Vout float32 `json:"vout,omitempty"`

	// Timestamp
	Ts float32 `json:"ts,omitempty"`

	// scriptPubKey
	ScriptPubKey string `json:"scriptPubKey,omitempty"`

	// NEBL amount
	Amount float32 `json:"amount,omitempty"`

	// Number of confirmations
	Confirmations float32 `json:"confirmations,omitempty"`
}
