/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GetTokenHoldersResponseHolders struct {

	Address string `json:"address,omitempty"`

	Amount float32 `json:"amount,omitempty"`
}
