/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GetTokenMetadataResponse struct {

	// ID of the token
	TokenId string `json:"tokenId,omitempty"`

	// Decimal places the token is divisible to
	Divisibility float32 `json:"divisibility,omitempty"`

	// Whether issuance of more tokens is locked
	LockStatus bool `json:"lockStatus,omitempty"`

	// Whether the tokens are aggregatable
	AggregationPolicy string `json:"aggregationPolicy,omitempty"`

	// Total number of tokens in supply
	TotalSupply float32 `json:"totalSupply,omitempty"`

	// Total number of addresses this token is held at
	NumOfHolders float32 `json:"numOfHolders,omitempty"`

	// Total number of transactions of this token
	NumOfTransfers float32 `json:"numOfTransfers,omitempty"`

	// Total number of times this token has been issued
	NumofIssuance float32 `json:"numofIssuance,omitempty"`

	// Number of times tokens have been burned
	NumOfBurns float32 `json:"numOfBurns,omitempty"`

	// Block number token was issued in
	FirstBlock float32 `json:"firstBlock,omitempty"`

	// TXID the token was issued with
	IssuanceTxid string `json:"issuanceTxid,omitempty"`

	// Address that issued the tokens
	IssueAddress string `json:"issueAddress,omitempty"`

	MetadataOfIssuance *GetTokenMetadataResponseMetadataOfIssuance `json:"metadataOfIssuance,omitempty"`

	MetadataOfUtxo *GetTokenMetadataResponseMetadataOfIssuance `json:"metadataOfUtxo,omitempty"`
}
