/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GetAddressInfoResponse struct {

	// The Neblio Address
	Address string `json:"address,omitempty"`

	// Array of UTXOs held at this address.
	Utxos []GetAddressInfoResponseUtxos `json:"utxos,omitempty"`
}
