/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GetTransactionInfoResponsePreviousOutput struct {

	Asm string `json:"asm,omitempty"`

	Hex string `json:"hex,omitempty"`

	ReqSigs float32 `json:"reqSigs,omitempty"`

	Type_ string `json:"type,omitempty"`

	Addresses []string `json:"addresses,omitempty"`
}
