/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GetTransactionInfoResponseScriptSig struct {

	Asm string `json:"asm,omitempty"`

	Hex string `json:"hex,omitempty"`
}
