/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Metadata set by user on token
type GetTokenMetadataResponseMetadataOfIssuanceDataUserData struct {

	Meta []GetTokenMetadataResponseMetadataOfIssuanceDataUserDataMeta `json:"meta,omitempty"`
}
