/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GetTokenIdResponse struct {

	// Unique ID of the token
	TokenId string `json:"tokenId,omitempty"`

	// String representing the token Symbol
	TokenName string `json:"tokenName,omitempty"`
}
