/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GetTokenMetadataResponseMetadataOfIssuanceDataUserDataMeta struct {

	Key string `json:"key,omitempty"`

	Value string `json:"value,omitempty"`
}
