/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type IssueTokenResponse struct {

	// TokenId of the to be issued token
	TokenId string `json:"tokenId,omitempty"`

	// Unsigned, raw transaction hex of the transaction to issue the token
	TxHex string `json:"txHex,omitempty"`
}
