/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type IssueTokenRequestMetadataRulesHolders struct {

	// Address that can hold the token
	Address string `json:"address,omitempty"`

	// Whether this rule can be modified in future transactions
	Locked bool `json:"locked,omitempty"`
}
