/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Object representing all metadata at token issuance
type IssueTokenRequestMetadata struct {

	// Token Symbol it will be identified by (ex. NIBBL)
	TokenName string `json:"tokenName,omitempty"`

	// Name of token issuer
	Issuer string `json:"issuer,omitempty"`

	// Long name or description of token (ex. Nibble)
	Description string `json:"description,omitempty"`

	Urls *IssueTokenRequestMetadataUrls `json:"urls,omitempty"`

	UserData *GetTokenMetadataResponseMetadataOfIssuanceDataUserData `json:"userData,omitempty"`

	// Array of encryption instruction objects for encrypting userData
	Encryptions []IssueTokenRequestMetadataEncryptions `json:"encryptions,omitempty"`

	Rules *IssueTokenRequestMetadataRules `json:"rules,omitempty"`
}
