/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type IssueTokenRequestMetadataRulesFeesItems struct {

	// Address fee is auto sent to
	Address string `json:"address,omitempty"`

	// How fee should be paid, either with a tokenId, or with NEBL if null
	TokenId string `json:"tokenId,omitempty"`

	// Amount of NTP1 token, or NEBL (in satoshi) to pay as fee
	Value string `json:"value,omitempty"`
}
