/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Object representing flags that potentialy modify this transaction
type IssueTokenRequestFlags struct {

	// If true change will be split into 2 outputs, one for NEBL change and one for NTP1 change (recommended)
	SplitChange bool `json:"splitChange,omitempty"`
}
