/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type IssueTokenRequestMetadataRulesFees struct {

	// Array of objects describing fee rules
	Items []IssueTokenRequestMetadataRulesFeesItems `json:"items,omitempty"`

	// Whether this rule can be modified in future transactions
	Locked bool `json:"locked,omitempty"`
}
