/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neblioapi

// Metadata set by user on token for UTXO
type GetTokenMetadataResponseMetadataOfUtxoUserData struct {
	Meta []map[string]interface{} `json:"meta,omitempty"`
}
