/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neblioapi

type GetBlockIndexResponse struct {
	// Hash of the requested block
	BlockHash string `json:"blockHash,omitempty"`
}
