/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neblioapi

type GetTxResponseVin struct {
	// TXID of the input
	Txid string `json:"txid,omitempty"`
	// output index
	Vout float32 `json:"vout,omitempty"`
	ScriptSig GetTransactionInfoResponseScriptSig `json:"scriptSig,omitempty"`
	Sequence float32 `json:"sequence,omitempty"`
	// Value of input in NEBL
	Value float32 `json:"value,omitempty"`
	// Value of input in NEBL satoshi
	ValueSat float32 `json:"valueSat,omitempty"`
	// input index
	N float32 `json:"n,omitempty"`
}
