/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neblioapi

type GetTokenMetadataResponse struct {
	// ID of the token
	TokenId string `json:"tokenId,omitempty"`
	// Example UTXO containing this token.
	SomeUtxo string `json:"someUtxo,omitempty"`
	// Decimal places the token is divisible to
	Divisibility float32 `json:"divisibility,omitempty"`
	// Whether issuance of more tokens is locked
	LockStatus bool `json:"lockStatus,omitempty"`
	// Whether the tokens are aggregatable
	AggregationPolicy string `json:"aggregationPolicy,omitempty"`
	// Total number of tokens in supply
	TotalSupply float32 `json:"totalSupply,omitempty"`
	// Total number of addresses this token is held at
	NumOfHolders float32 `json:"numOfHolders,omitempty"`
	// Total number of transactions of this token
	NumOfTransfers float32 `json:"numOfTransfers,omitempty"`
	// Total number of times this token has been issued
	NumOfIssuance float32 `json:"numOfIssuance,omitempty"`
	// Number of times tokens have been burned
	NumOfBurns float32 `json:"numOfBurns,omitempty"`
	// Block number token was issued in
	FirstBlock float32 `json:"firstBlock,omitempty"`
	// TXID the token was issued with
	IssuanceTxid string `json:"issuanceTxid,omitempty"`
	// Address that issued the tokens
	IssueAddress string `json:"issueAddress,omitempty"`
	MetadataOfIssuence GetTokenMetadataResponseMetadataOfIssuence `json:"metadataOfIssuence,omitempty"`
	MetadataOfUtxo GetTokenMetadataResponseMetadataOfUtxo `json:"metadataOfUtxo,omitempty"`
}
