/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neblioapi

type GetAddressInfoResponseUtxos struct {
	// Index of the UTXO at this address
	Index float32 `json:"index,omitempty"`
	// Txid of this UTXO
	Txid string `json:"txid,omitempty"`
	// Blockheight of the UTXO
	Blockheight float32 `json:"blockheight,omitempty"`
	// Blocktime of the UTXO
	Blocktime float32 `json:"blocktime,omitempty"`
	// Object representing the scruptPubKey of the UTXO
	ScriptPubKey map[string]interface{} `json:"scriptPubKey,omitempty"`
	// Whether the UTXO has been used
	Used bool `json:"used,omitempty"`
	// Value of the UTXO in NEBL satoshi
	Value float32 `json:"value,omitempty"`
	// Array of NTP1 tokens in this UTXO.
	Tokens []GetAddressInfoResponseTokens `json:"tokens,omitempty"`
}
