/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neblioapi

// Metadata set for UTXO
type GetTokenMetadataResponseMetadataOfUtxo struct {
	UserData GetTokenMetadataResponseMetadataOfUtxoUserData `json:"userData,omitempty"`
}
