/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neblioapi

type GetAddressInfoResponse struct {
	// The Neblio Address
	Address string `json:"address,omitempty"`
	// Array of UTXOs held at this address.
	Utxos []GetAddressInfoResponseUtxos `json:"utxos,omitempty"`
}
