/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neblioapi

type SendTokenRequest struct {
	// Fee in satoshi to include in the issuance transaction min 10000 (0.0001 NEBL)
	Fee float32 `json:"fee"`
	// Array of addresses to send the token from
	From []string `json:"from,omitempty"`
	// Array of UTXOs to send the token from
	Sendutxo []string `json:"sendutxo,omitempty"`
	To []SendTokenRequestTo `json:"to"`
	Flags IssueTokenRequestFlags `json:"flags,omitempty"`
	Metadata IssueTokenRequestMetadata `json:"metadata,omitempty"`
}
