/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neblioapi

type GetTokenMetadataResponseMetadataOfIssuenceData struct {
	// Token symbol
	TokenName string `json:"tokenName,omitempty"`
	// Name of token issuer
	Issuer string `json:"issuer,omitempty"`
	// Token description
	Description string `json:"description,omitempty"`
	UserData GetTokenMetadataResponseMetadataOfIssuenceDataUserData `json:"userData,omitempty"`
}
