/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neblioapi

type SendTokenResponse struct {
	// Unsigned, raw transaction hex of the transaction to send the token
	TxHex string `json:"txHex,omitempty"`
	// Array of indexes transfering NTP1 tokens
	Ntp1OutputIndexes []float32 `json:"ntp1OutputIndexes,omitempty"`
	// Array of indexes of multisig outputs
	MultisigOutputs []float32 `json:"multisigOutputs,omitempty"`
}
