/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelError struct {

	Code int32 `json:"code,omitempty"`

	Message string `json:"message,omitempty"`

	Fields string `json:"fields,omitempty"`
}
