/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neblioapi

type SendTxRequest struct {
	// Signed raw tx hex to broadcast
	TxHex string `json:"txHex,omitempty"`
}
