/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neblioapi

type IssueTokenRequestMetadataRulesHolders struct {
	// Address that can hold the token
	Address string `json:"address,omitempty"`
	// Whether this rule can be modified in future transactions
	Locked bool `json:"locked,omitempty"`
}
