/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neblioapi

type GetRawTxResponse struct {
	// Raw hex representing the transaction
	Rawtx string `json:"rawtx,omitempty"`
}
