/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neblioapi

// Object describing token rules
type IssueTokenRequestMetadataRules struct {
	Fees IssueTokenRequestMetadataRulesFees `json:"fees,omitempty"`
	// Array of objects describing what addresses can hold the token
	Holders []IssueTokenRequestMetadataRulesHolders `json:"holders,omitempty"`
	Expiration IssueTokenRequestMetadataRulesExpiration `json:"expiration,omitempty"`
}
