/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neblioapi

// Metadata set at issuance
type GetTokenMetadataResponseMetadataOfIssuence struct {
	Data GetTokenMetadataResponseMetadataOfIssuenceData `json:"data,omitempty"`
}
