/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neblioapi

// Object containing the JSON response from the Neblio node.
type RpcResponse struct {
	// Object containing the response output.
	Result map[string]interface{} `json:"result,omitempty"`
	// Identifier of RCP caller
	Id string `json:"id,omitempty"`
	// Object containing any error information.
	Error map[string]interface{} `json:"error,omitempty"`
}
