/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neblioapi

// Metadata set at issuance
type GetTokenMetadataResponseMetadataOfIssuance struct {
	Data GetTokenMetadataResponseMetadataOfIssuanceData `json:"data,omitempty"`
}
