/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.2.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neblioapi

type IssueTokenRequestTransfer struct {
	// Address to send the amount of issued tokens to
	Address string `json:"address,omitempty"`
	Amount float32 `json:"amount,omitempty"`
}
