/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neblioapi

type GetTokenIdResponse struct {
	// Unique ID of the token
	TokenId string `json:"tokenId,omitempty"`
	// String representing the token Symbol
	TokenName string `json:"tokenName,omitempty"`
}
