/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.2.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neblioapi

type BroadcastTxResponse struct {
	// Txid of successfully broadcasted transaction
	Txid string `json:"txid,omitempty"`
}
