/*
 * Neblio REST API Suite
 *
 * APIs for Interacting with NTP1 Tokens & The Neblio Blockchain
 *
 * API version: 1.2.4
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neblioapi

// Object representing flags that potentialy modify this transaction
type IssueTokenRequestFlags struct {
	// If true change will be split into 2 outputs, one for NEBL change and one for NTP1 change (recommended)
	SplitChange bool `json:"splitChange,omitempty"`
}
